EPrescription.Web/Controllers/MedicineController.cs
using EPrescription.Entities;
using EPrescription.Services;
using EPrescription.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EPrescription.Web.Controllers
{
    [Authorize]
    public class MedicineController : Controller
    {
        // GET: Medicine
        public ActionResult Index(MedicineViewModel model)
        {
            model.MedicinePagedList = new MedicineModel().GetAllIPagedMedicine(model.Page, model.PageSize, model.Name, model.CompanyId, model.GenericName);
            return View(model);
        }
        public ActionResult Add()
        {
            return View(new MedicineModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MedicineModel model)
        {
            model.Add();
            return RedirectToAction("Index");
        }
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase ExcelFile)
        {  
            string msg= new MedicineModel().UploadExcel(ExcelFile);
            ModelState.AddModelError("", msg);
            return View();
        }

        public JsonResult LoadMedicineName(string name)
        {
            var list = new MedicineModel().GetMedicineNameByStr(name);
            return Json(new { list },JsonRequestBehavior.AllowGet);
        }
        public JsonResult LoadAvailablity(string medicineName)
        {
            if (string.IsNullOrEmpty(medicineName))
                return Json(new { list = new List<string>() }, JsonRequestBehavior.AllowGet);
            var list = new MedicineModel().GetAvailablity(medicineName) ?? Enumerable.Empty<string>();
            return Json(new { list }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UploadConfig()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadConfig(HttpPostedFileBase ExcelFile)
        {
            new MedicineModel().UploadConfigExcel(ExcelFile);
            return View();
        }
        public ActionResult Edit(int id)
        {
            var medicineModel = new MedicineModel().Edit(id);
            if (medicineModel == null)
            {
                return HttpNotFound();
            }
            return View(medicineModel); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MedicineModel model)
        {
            if (ModelState.IsValid)
            {
                model.Edit(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Inactive(MedicineModel model)
        {
            model.Inactive();
            return RedirectToAction("Index");
        }
    }
}

EPrescription.Web/Views/Medicine/Add.cshtml
@model EPrescription.Web.Models.MedicineModel
@{
    ViewBag.Title = "Add";
}
@Styles.Render("~/Content/select2")
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        @using (Html.BeginForm("Add", "Medicine", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Medicine Add</h3>

                    <div class="box-tools pull-right">

                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <a href="@Url.Action("Index", "User")" class="btn btn-box-tool" title="Remove">
                            <i class="fa fa-times"></i>
                        </a>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="form-group ">
                                    @Html.LabelFor(model => model.BrandName, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(model => model.BrandName, new { @class = "form-control", @placeholder = "Brand Name" })
                                        @Html.ValidationMessageFor(model => model.BrandName)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MedicineManufacturerId, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(model => model.MedicineManufacturerId, new SelectList(Model.MedicineManufactureList, "Id", "CompanyName"), new { @class = "form-control select2" })
                                        @Html.ValidationMessageFor(model => model.MedicineManufacturerId)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.GenericNameIds, new { @class = "col-sm-4 control-label text-left " })
                                    <div class="col-sm-8">
                                        @Html.ListBoxFor(model => model.GenericNameIds, new SelectList(Model.GenericNameList, "Id", "TypeName"), new { @class = "form-control select2" })
                                        @Html.ValidationMessageFor(model => model.GenericNameIds)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.StrengthIds, new { @class = "col-sm-4 control-label text-left " })
                                    <div class="col-sm-8">
                                        @Html.ListBoxFor(model => model.StrengthIds, new SelectList(Model.StrengthList, "Id", "StrengthName"), new { @class = "form-control select2" })
                                        @Html.ValidationMessageFor(model => model.StrengthIds)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DosageIds, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(model => model.DosageIds, new SelectList(Model.DosageTypeList, "Id", "TypeName"), new { @class = "form-control select2", @multiple = true })
                                        @Html.ValidationMessageFor(model => model.DosageIds)
                                    </div>
                                </div>


                            </div>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    @Html.LabelFor(model => model.Dar, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextAreaFor(model => model.Dar, new { @class = "form-control", @placeholder = "DAR" })
                                        @Html.ValidationMessageFor(model => model.Dar)
                                    </div>
                                </div>

                            </div>
                            <!--/.col (right) -->

                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index","Medicine")" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
                <!-- /.box-footer-->
            </div>
        }
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/select2")
    <script>
        $(".select2").select2({
            placeholder: "---Select---",
            allowClear: true,
            width: '100%'
        });
    </script>
}

EPrescription.Web/Views/Medicine/Edit.cshtml
@model EPrescription.Web.Models.MedicineModel
@{
    ViewBag.Title = "Edit";
}
@Styles.Render("~/Content/select2")
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        @using (Html.BeginForm("Edit", "Medicine", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Medicine</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <a href="@Url.Action("Index", "Medicine")" class="btn btn-box-tool" title="Remove">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <!-- Hidden field for MedicineId -->
                                @Html.HiddenFor(model => model.Id)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.BrandName, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(model => model.BrandName, new { @class = "form-control", @placeholder = "Brand Name" })
                                        @Html.ValidationMessageFor(model => model.BrandName)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MedicineManufacturerId, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(
                                            model => model.MedicineManufacturerId,
                                            new SelectList(Model.MedicineManufactureList, "Id", "CompanyName", Model.MedicineManufacturerId),
                                            new { @class = "form-control select2" }
                                        )
                                        @Html.ValidationMessageFor(model => model.MedicineManufacturerId)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(Model => Model.GenericNameIds, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.ListBoxFor(
                                            Model => Model.GenericNameIds,
                                            new MultiSelectList(Model.GenericNameList, "Id", "TypeName", Model.GenericNameIds),
                                            new { @class = "form-control select2" }
                                        )
                                        @Html.ValidationMessageFor(model => model.GenericNameIds)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.StrengthIds, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.ListBoxFor(
                                            model => model.StrengthIds,
                                            new MultiSelectList(Model.StrengthList, "Id", "StrengthName", Model.StrengthIds),
                                            new { @class = "form-control select2" }
                                        )
                                        @Html.ValidationMessageFor(model => model.StrengthIds)
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.DosageIds, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.ListBoxFor(
                                            model => model.DosageIds,
                                            new MultiSelectList(Model.DosageTypeList, "Id", "TypeName", Model.DosageIds),
                                            new { @class = "form-control select2" }
                                        )
                                        @Html.ValidationMessageFor(model => model.DosageIds)
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Dar, new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextAreaFor(model => model.Dar, new { @class = "form-control", @placeholder = "DAR" })
                                        @Html.ValidationMessageFor(model => model.Dar)
                                    </div>
                                </div>
                            </div>
                            <!--/.col (right) -->
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index", "Medicine")" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
                <!-- /.box-footer-->
            </div>
        }
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/select2")
    <script>
        $(".select2").select2({
        placeholder: "---Select---",
        allowClear: true,
        width: '100%'
        });
        $(".select2").each(function () {
            var selectedValues = $(this).val();
            $(this).val(selectedValues).trigger("change");
        });
    </script>
}

EPrescription.Web/Views/Medicine/Index.cshtml
@model EPrescription.Web.Models.MedicineViewModel
@using EPrescription.Common
@using PagedList.Mvc
@{
    ViewBag.Title = "Medicines";
}
@Styles.Render("~/Content/PagedList.css")
<div class="content-wrapper">
    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Medicines</h3>
                <div class="box-tools pull-right">
                    <a href="@Url.Action("Add", "Medicine")" class="btn btn-box-tool" title="Add" data-toggle="tooltip">
                        <i class="fa fa-plus"></i>
                    </a>
                    <a href="@Url.Action("Upload", "Medicine")" class="btn btn-box-tool" title="Upload" data-toggle="tooltip">
                        <i class="fa fa-upload"></i>
                    </a>
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <a href="@Url.Action("Index", "Home")" class="btn btn-box-tool" title="Remove">
                        <i class="fa fa-times"></i>
                    </a>

                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered">
                            <thead>
                                <tr class="text-bold text-blue">
                                    <th>@Html.DisplayNameFor(model => model.MedicinePagedList.FirstOrDefault().BrandName)</th>
                                    <th>@Html.DisplayNameFor(model => model.MedicinePagedList.FirstOrDefault().MedicineManufacturerId)</th>
                                    <th>@Html.DisplayName("Generic Name")</th>
                                    <th>@Html.DisplayName("Strengths")</th>
                                    <th>@Html.DisplayName("Dosage Types")</th>
                                    <th>@Html.DisplayNameFor(model => model.MedicinePagedList.FirstOrDefault().Dar)</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.MedicinePagedList)
                                {
                                    <tr>
                                        <td>
                                            <small>
                                                @Html.DisplayFor(itemElement => item.BrandName)
                                            </small>
                                        </td>
                                        <td>
                                            <small>
                                                @Html.DisplayFor(itemElement => item.MedicineManufacturer.CompanyName)
                                            </small>
                                        </td>

                                        <td>
                                            <small>
                                                @item.GenericNameMedicineRelations.Where(s => s.StatusFlag == (byte)EnumActiveDeative.Active).Select(s => s.GenericName.TypeName).JoinString(" +")
                                            </small>
                                        </td>
                                        <td>
                                            <small>
                                                @item.StrengthMedicineRelations.Where(s => s.StatusFlag == (byte)EnumActiveDeative.Active).Select(s => s.Strength.StrengthName).JoinString(" +")
                                            </small>
                                        </td>
                                        <td>
                                            <small>
                                                @item.DosageTypeMedicineRelations.Where(s => s.StatusFlag == (byte)EnumActiveDeative.Active).Select(s => s.DosageType.TypeName).JoinString(" +")
                                            </small>
                                        </td>
                                        <td><small> @Html.DisplayFor(itemElement => item.Dar)</small> </td>

                                        <td>
                                            @if (item.StatusFlag.IsActive())
                                            {
                                                <a href="@Url.Action("Edit","Medicine",new { @id=item.Id})" class="btn btn-sm btn-success"> <i class="fa fa-edit"></i></a>
                                                <a data-toggle="modal" data-target="#@item.Id" class="btn btn-sm btn-danger"> <i class="fa fa-ban"></i></a>
                                                <div class="modal modal-danger fade in" id="@item.Id">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                <h4 class="modal-title">Confirm</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>
                                                                    Are you sure you want to Inactive this Medicine?
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                                                                <a href="@Url.Action("Inactive","Medicine",new { id=item.Id})" class="btn btn-outline">Confirm</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        
                    </div>
                   
                </div>
            </div>
            <div class="box-footer">
                <a href="@Url.Action("Index","Home")" class="btn btn-danger">Cancel</a>
                <div class="main-pagination pull-right">

                    @Html.PagedListPager(Model.MedicinePagedList, Page => Url.Action("Index", "Medicine", new RouteValueDictionary() { { "Page", Page }, { "PageSize", Model.PageSize }, { "Name", Model.Name }, { "GenericName", Model.GenericName }, { "CompanyId", Model.CompanyId } }))
                    Page @(Model.MedicinePagedList.PageCount < Model.MedicinePagedList.PageNumber ? 0 : Model.MedicinePagedList.PageNumber) of @Model.MedicinePagedList.PageCount
                </div>
            </div>
        </div>
    </section>
</div>

EPrescription.Web/Views/Medicine/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        @using (Html.BeginForm("Upload", "Medicine", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Medicine Upload</h3>

                    <div class="box-tools pull-right">

                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <a href="@Url.Action("Index", "User")" class="btn btn-box-tool" title="Remove">
                            <i class="fa fa-times"></i>
                        </a>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                         
                            <div class="col-md-6">
                                <div class="form-group ">
                                    @Html.Label("Excel File", new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextBox("ExcelFile",null, new { @class = "form-control",type="file",required="required" })
                                        @Html.ValidationMessage("ExcelFile")
                                    </div>
                                </div>

                            </div>
                            <!--/.col (right) -->

                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index","Medicine")" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
                <!-- /.box-footer-->
            </div>
        }
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   
}

EPrescription.Web/Views/Medicine/UploadConfig.cshtml
@{
    ViewBag.Title = "Upload";
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        @using (Html.BeginForm("UploadConfig", "Medicine", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Config Upload</h3>

                    <div class="box-tools pull-right">

                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <a href="@Url.Action("Index", "User")" class="btn btn-box-tool" title="Remove">
                            <i class="fa fa-times"></i>
                        </a>

                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="col-md-6">
                                <div class="form-group ">
                                    @Html.Label("Excel File", new { @class = "col-sm-4 control-label text-left" })
                                    <div class="col-sm-8">
                                        @Html.TextBox("ExcelFile", null, new { @class = "form-control", type = "file", required = "required" })
                                        @Html.ValidationMessage("ExcelFile")
                                    </div>
                                </div>

                            </div>
                            <!--/.col (right) -->

                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index","Medicine")" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
                <!-- /.box-footer-->
            </div>
        }
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}