EPrescription.Web/Controllers/ProcedureController.cs
using EPrescription.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EPrescription.Web.Controllers
{
    [Authorize]
    public class ProcedureController : Controller
    {
        // GET: Procedure
        public ActionResult Index()
        {
            return View(new ProcedureModel().GetAllProcedures());
        }
        public ActionResult Add(ProcedureModel model)
        {
            model.Add();
            return RedirectToAction("Index");
        }
        public JsonResult IsProcedureNameExist(string ProcedureName, string InitialProcedureNmae)
        {
            bool isNotExist = new ProcedureModel().IsProcedureNameExist(ProcedureName, InitialProcedureNmae);
            return Json(isNotExist, JsonRequestBehavior.AllowGet);
        }
        public ActionResult LoadProcedure(int id)
        {
            var model = new ProcedureModel(id);
            return Json(new { ProcedureName = model.ProcedureName, Id = model.Id });
        }
        public ActionResult Edit(ProcedureModel model)
        {
            model.Edit();
            return RedirectToAction("Index");
        }
        public ActionResult Inactive(ProcedureModel model)
        {
            model.Inactive();
            return RedirectToAction("Index");
        }
    }
}

EPrescription.Web/Views/Procedure/Index.cshtml
@model IEnumerable<EPrescription.Entities.Procedure>
@using EPrescription.Common
@using EPrescription.Web.Models
@{
    ViewBag.Title = "Procedures";
}
<div class="content-wrapper">
    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Procedures</h3>
                <div class="box-tools pull-right">

                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <a href="@Url.Action("Index", "Home")" class="btn btn-box-tool" title="Remove">
                        <i class="fa fa-times"></i>
                    </a>

                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-8">
                        <table class="table table-bordered">
                            <thead>
                                <tr class="text-bold text-blue">
                                    <th>@Html.DisplayNameFor(model => model.FirstOrDefault().ProcedureName)</th>
                                    <th>@Html.DisplayNameFor(model => model.FirstOrDefault().UpdatedAt)</th>
                                    <th>@Html.DisplayNameFor(model => model.FirstOrDefault().StatusFlag)</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(itemElement => item.ProcedureName)</td>
                                        <td>@item.UpdatedAt.DateFormat()</td>
                                        <td>@item.StatusFlag.StatusString()</td>
                                        <td>
                                            @if (item.StatusFlag.IsActive())
                                            {
                                                <a onclick="getDataForEdit('@item.Id')" class="btn btn-sm btn-success"> <i class="fa fa-edit"></i></a>
                                                <a data-toggle="modal" data-target="#@item.Id" class="btn btn-sm btn-danger"> <i class="fa fa-ban"></i></a>
                                                <div class="modal modal-danger fade in" id="@item.Id">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                <h4 class="modal-title">Confirm</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>
                                                                    Are you sure you want to Inactive this Procedure?
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                                                                <a href="@Url.Action("Inactive","Procedure",new { id=item.Id})" class="btn btn-outline">Confirm</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                    <div class="col-md-4">
                        @{
                            var proceduresModel = new ProcedureModel();
                        }
                        @Html.Partial("_procedurePartial", proceduresModel)
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="@Url.Action("Index","Home")" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </section>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jquery-val")
    @Scripts.Render("~/bundles/ajaxCall")
    <script>
      function getDataForEdit(id) {
                var url = '@Url.Action("LoadProcedure", "Procedure")';
                var paramData = { id: id };
                ajaxCall(url, paramData, "renderProcedureLoad");
    }
    function renderProcedureLoad(data) {
        var editUrl = '@Url.Action("Edit", "Procedure")';
                $('#procedureForm').attr('action', editUrl);
                $("#Id").val(data.Id);
                $("#InitialProcedureName").val(data.ProcedureName);
                $("#ProcedureName").val(data.ProcedureName);
                $("#submitBtn").html('<i class="fa fa-save"></i> Update');
    }
    </script>
}

EPrescription.Web/Views/Procedure/_procedurePartial.cshtml
@model EPrescription.Web.Models.ProcedureModel
@using (Html.BeginForm("Add", "Procedure", FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data", @id = "procedureForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.Hidden("InitialProcedureName", "undefined")
    @Html.HiddenFor(model => model.Id)
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Add/Edit</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProcedureName, new { @class = "col-sm-5 control-label text-left" })
                        <div class="col-sm-7">
                            @Html.TextBoxFor(model => model.ProcedureName, new { @class = "form-control", @placeholder = "Name" })
                            @Html.ValidationMessageFor(model => model.ProcedureName)
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="box-footer">
            <a href="@Url.Action("Index","Procedure")" class="btn btn-warning">Cancel</a>
            <button id="submitBtn" type="submit" class="btn btn-info pull-right">Save</button>
        </div>
    </div>
}